name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: AudreyTan03
          outputs: |
            dist/snake.svg?color_snake=FF69B4&color_dots=#FFF0F5,#FFD1DC,#FFB6C1,#FF69B4,#C71585
            dist/snake-dark.svg?color_snake=FF69B4&color_dots=#130820,#2a0d35,#6b2d5e,#FF69B4,#FF1493

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
